#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros -Q dynamic-space-size=400 -- $0 "$@"
|#

(ql:quickload '(:uiop :quickdocs-extracter) :silent t)

(use-package :quickdocs-extracter.util)

(defun main (&optional name (ql-dist-version (ql-dist:version (ql-dist:dist "quicklisp"))))
  (unless name
    (format *error-output* "~&Usage: extract-system <system name> [<ql dist version>]~%")
    (uiop:quit -1))
  
  (let ((sb-impl::*default-external-format* :utf-8)
        (sb-alien::*default-c-string-external-format* :utf-8))
    (with-ql-dist ql-dist-version
      (prin1 (let ((*standard-output* *error-output*)
                   (*trace-output* *error-output*))
               (quickdocs-extracter:serialize-system name))))))
